parameters:
- name: TestFilter
  type: string
  default: TestCategory=livesmoketest

trigger: none
pr: none

variables:
- group: LIVE das-live-smoke-test-suite

extends:
  template: ../../pipeline-templates/resource-template.yml
  parameters:
    TestFilter: ${{ parameters.TestFilter }}
    TestDlls: $(Pipeline.Workspace)/$(VariableFromGroup)/das-enterprise-automation-test-suite/drop/tests/SFA.DAS.Live.SmokeTests/SFA.DAS.Live.SmokeTests.dll
