trigger: none

extends:
  template: ../../pipeline-templates/resource-template.yml
  parameters:
    TestCategory: apprenticecommitmentsapi
    TestDlls: $(Pipeline.Workspace)/das-enterprise-automation-test-suite/drop/tests/SFA.DAS.ApprenticeCommitments.APITests/SFA.DAS.ApprenticeCommitments.APITests.dl
