parameters:
- name: TestFilter
  type: string
  default: TestCategory=apprenticecommitmentsapi

trigger: none
pr: none

schedules:
- cron: "0 3 * * 1-5"
  displayName: Daily midnight run
  branches:
    include:
    - master
  always: true

extends:
  template: ../../pipeline-templates/resource-template.yml
  parameters:
    TestFilter: ${{ parameters.TestFilter }}
    TestDlls: $(Pipeline.Workspace)/das-enterprise-automation-test-suite/drop/tests/SFA.DAS.ApprenticeCommitments.APITests/SFA.DAS.ApprenticeCommitments.APITests.dll
