trigger: none

variables:
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- name: TestCategory
  value: apprenticecommitmentsapi
- group: Release Automation Suite Variables
- group: Release Automation Suite Variables (Db)
resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.0.3
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.2
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-enterprise-automation-test-suite
    project: Digital Apprenticeship Service
    source: das-enterprise-automation-test-suite
    branch: master
    trigger:
      stages:
      - Deploy_PP

stages:
- stage: Deploy_TEST
  displayName: Run test suite on TEST
  variables:
  - group: RELEASE QTY_das-apprentice-commitments-api-automation-test-suite 
  - group: TEST Automation Suite Variables
  - group: TEST DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/test-api.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM
- stage: Deploy_TEST2
  displayName: Run test suite on TEST2
  variables:
  - group: RELEASE QTY_das-apprentice-commitments-api-automation-test-suite
  - group: TEST2 DevTest Shared Resources
  - group: TEST2 Automation Suite Variables
  jobs:
  - template: pipeline-templates/job/test-api.yml
    parameters:
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM
- stage: Deploy_PP
  displayName: Run test suite on PP
  variables:
  - group: PREPROD QTY_das-apprentice-commitments-api-automation-test-suite
  - group: PreProd Shared Resources
  - group: PreProd Automation Suite Variables
  jobs:
  - template: pipeline-templates/job/test-api.yml
    parameters:
      Environment: PP
      ServiceConnection: SFA-DIG-PreProd-ARM